// Code generated by go-bindata.
// sources:
// ../db_migrations/001_initial.sql
// DO NOT EDIT!

package migrations

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _db_migrations001_initialSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x91\xcb\x6a\xc3\x30\x10\x45\xf7\xf3\x15\x77\x19\xd3\x04\xd2\xd2\xac\xbc\x52\xe3\x81\x9a\x3a\x72\x2a\xe4\x92\xac\x8c\x40\x42\x08\x1a\x37\x4d\x65\xda\xfe\x7d\xc9\xb3\xce\xc3\x3b\x49\x97\x7b\xce\xa0\x19\x8d\x70\xb7\x0a\x7e\x63\xa2\x43\xb5\xa6\xa9\x62\xa1\x19\x5a\x3c\x15\x8c\xb0\x32\xde\x7d\x61\x40\x40\xb0\x78\x13\x6a\xfa\x2c\xd4\xe0\x71\x9c\x60\xae\xf2\x99\x50\x4b\xbc\xf0\x72\x48\x40\xbb\x79\x87\xe6\x85\xde\x9e\x8d\xb5\xce\xd6\x26\x22\x13\x9a\x75\x3e\x63\xc8\x52\x43\x56\x45\xb1\x4d\xe3\xef\xda\x9d\x48\xf7\xe3\x84\x92\x94\x6e\x48\xeb\x68\xfc\x41\xbc\xbb\x5e\xe8\xcf\x88\xc6\x9f\xb2\x87\xc9\xe4\x3f\xec\xa2\x73\x99\xf1\xa2\x83\xae\x43\x63\xdd\x0f\x4a\x79\xa6\x8b\xc6\x27\xe9\xb1\x52\xc9\xfc\xb5\xba\xd1\x6c\x9b\xf0\xd9\xba\xcb\xea\x71\xcc\x21\xf6\x10\xea\xfe\x6b\xf6\xf1\xdd\x50\xa6\xca\x79\xcf\x1c\x69\x4f\xb8\x57\x1d\xd2\xee\x4a\xae\x9f\x76\x85\x94\xfe\x02\x00\x00\xff\xff\x35\xac\xe9\xbf\xce\x01\x00\x00")

func db_migrations001_initialSqlBytes() ([]byte, error) {
	return bindataRead(
		_db_migrations001_initialSql,
		"db_migrations/001_initial.sql",
	)
}

func db_migrations001_initialSql() (*asset, error) {
	bytes, err := db_migrations001_initialSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "db_migrations/001_initial.sql", size: 462, mode: os.FileMode(420), modTime: time.Unix(1507140102, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"db_migrations/001_initial.sql": db_migrations001_initialSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"db_migrations": &bintree{nil, map[string]*bintree{
		"001_initial.sql": &bintree{db_migrations001_initialSql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

